version: '3.3'
services:
  app:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=12345678
      - DB_SYNC=Y
    ports:
      - 3000:3000
    

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - '127.0.0.1:5432:5432'